import { AlertTriangle, Info } from 'lucide-react';
import { Alert, AlertDescription } from '@/components/ui/alert';
import { Badge } from '@/components/ui/badge';

interface AIDisclaimerProps {
  variant?: 'warning' | 'info';
  size?: 'sm' | 'md' | 'lg';
  showBadge?: boolean;
  customMessage?: string;
}

const AIDisclaimer = ({ 
  variant = 'warning', 
  size = 'md', 
  showBadge = true,
  customMessage 
}: AIDisclaimerProps) => {
  const getContent = () => {
    if (customMessage) return customMessage;
    
    switch (variant) {
      case 'info':
        return "This analysis is generated by AI and is for informational purposes only. User discretion is advised. For more accurate or personalized information, we recommend consulting with a licensed financial professional. All data is fully encrypted and handled securely.";
      case 'warning':
      default:
        return "⚠️ AI-generated analysis may contain inaccuracies. User discretion is advised. For more accurate or personalized information, we recommend consulting with a licensed financial professional. All data is fully encrypted and handled securely.";
    }
  };

  const getAlertVariant = () => {
    return variant === 'warning' ? 'destructive' : 'default';
  };

  const sizeClasses = {
    sm: 'text-xs p-2',
    md: 'text-sm p-3',
    lg: 'text-base p-4'
  };

  if (showBadge && size === 'sm') {
    return (
      <Badge variant="outline" className="text-xs bg-orange-50 text-orange-800 border-orange-200">
        <AlertTriangle className="w-3 h-3 mr-1" />
        AI Analysis - User Discretion Advised
      </Badge>
    );
  }

  return (
    <Alert variant={getAlertVariant()} className={sizeClasses[size]}>
      {variant === 'warning' ? (
        <AlertTriangle className="h-4 w-4" />
      ) : (
        <Info className="h-4 w-4" />
      )}
      <AlertDescription className="text-sm">
        {getContent()}
      </AlertDescription>
    </Alert>
  );
};

export default AIDisclaimer;