import { useState, useEffect } from 'react';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Tooltip, TooltipContent, TooltipProvider, TooltipTrigger } from '@/components/ui/tooltip';
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle, DialogTrigger } from '@/components/ui/dialog';
import { HelpCircle, Calculator, TrendingUp, DollarSign, Download, BarChart3 } from 'lucide-react';
import { useAuth } from '@/hooks/useAuth';
import { useCredits } from '@/hooks/useCredits';
import { supabase } from '@/integrations/supabase/client';
import { toast } from '@/hooks/use-toast';
import jsPDF from 'jspdf';
import html2canvas from 'html2canvas';
import ScenarioSimulator from './ScenarioSimulator';

interface FinancialMetric {
  label: string;
  value: number;
  explanation: string;
  category: 'revenue' | 'expense' | 'profit' | 'ratio';
}

const InteractiveFinancialModel = () => {
  const { user } = useAuth();
  const { trackDownload } = useCredits();
  const [metrics, setMetrics] = useState<FinancialMetric[]>([]);
  const [isExporting, setIsExporting] = useState(false);
  const [showScenario, setShowScenario] = useState(false);

  useEffect(() => {
    if (user) {
      loadRealFinancialData();
    }
  }, [user]);

  // Listen for financial data updates (document uploads)
  useEffect(() => {
    if (!user) return;

    const channel = supabase
      .channel('financial-data-changes')
      .on(
        'postgres_changes',
        {
          event: 'INSERT',
          schema: 'public',
          table: 'financial_data',
          filter: `user_id=eq.${user.id}`
        },
        () => {
          console.log('New financial data detected, refreshing model...');
          loadRealFinancialData();
        }
      )
      .on(
        'postgres_changes',
        {
          event: 'UPDATE',
          schema: 'public',
          table: 'financial_data',
          filter: `user_id=eq.${user.id}`
        },
        () => {
          console.log('Financial data updated, refreshing model...');
          loadRealFinancialData();
        }
      )
      .subscribe();

    return () => {
      supabase.removeChannel(channel);
    };
  }, [user]);

  const loadRealFinancialData = async () => {
    if (!user) return;

    try {
      // Get recent financial data
      const { data: finData } = await supabase
        .from('financial_data')
        .select('*')
        .eq('user_id', user.id)
        .order('created_at', { ascending: false })
        .limit(10);

      if (finData && finData.length > 0) {
        const totalRevenue = finData.reduce((sum, record) => sum + (record.revenue || 0), 0);
        const totalExpenses = finData.reduce((sum, record) => sum + (record.expenses || 0), 0);
        const totalCashFlow = finData.reduce((sum, record) => sum + (record.cash_flow || 0), 0);
        const grossProfit = totalRevenue * 0.6; // Assuming 60% gross margin
        const netIncome = totalRevenue - totalExpenses;
        const profitMargin = totalRevenue > 0 ? (netIncome / totalRevenue) * 100 : 0;
        const cashRunway = totalCashFlow > 0 ? Math.floor(totalCashFlow / (totalExpenses / 12)) : 0;

        const updatedMetrics: FinancialMetric[] = [
          {
            label: 'Total Revenue',
            value: totalRevenue,
            explanation: `Your total income from sales over the analyzed period. ${totalRevenue > 100000 ? 'Strong revenue base for growth.' : 'Consider strategies to increase revenue streams.'}`,
            category: 'revenue'
          },
          {
            label: 'Total Expenses',
            value: totalExpenses,
            explanation: `Total operational costs including COGS, salaries, and overhead. ${totalExpenses < totalRevenue * 0.8 ? 'Good expense control.' : 'Review expenses for optimization opportunities.'}`,
            category: 'expense'
          },
          {
            label: 'Net Income',
            value: netIncome,
            explanation: `Final profit after all expenses. ${netIncome > 0 ? 'Profitable operations indicate healthy business.' : 'Focus on improving profitability through revenue growth or cost reduction.'}`,
            category: 'profit'
          },
          {
            label: 'Cash Flow',
            value: totalCashFlow,
            explanation: `Actual cash generated by operations. ${totalCashFlow > netIncome ? 'Positive cash flow timing benefits.' : 'Monitor cash flow patterns for working capital needs.'}`,
            category: 'profit'
          },
          {
            label: 'Profit Margin',
            value: Math.round(profitMargin),
            explanation: `Net income as percentage of revenue. ${profitMargin > 15 ? 'Excellent' : profitMargin > 10 ? 'Good' : 'Needs improvement'} profitability for your business type.`,
            category: 'ratio'
          },
          {
            label: 'Cash Runway',
            value: Math.max(cashRunway, 0),
            explanation: `Months of expenses covered by current cash position. ${cashRunway > 6 ? 'Strong' : cashRunway > 3 ? 'Adequate' : 'Limited'} financial cushion for operations.`,
            category: 'ratio'
          }
        ];

        setMetrics(updatedMetrics);
      }
    } catch (error) {
      console.error('Error loading financial data:', error);
    }
  };

  const getCategoryColor = (category: string) => {
    switch (category) {
      case 'revenue': return 'text-success';
      case 'expense': return 'text-destructive';
      case 'profit': return 'text-primary';
      case 'ratio': return 'text-accent';
      default: return 'text-muted-foreground';
    }
  };

  const getCategoryBg = (category: string) => {
    switch (category) {
      case 'revenue': return 'bg-success/10';
      case 'expense': return 'bg-destructive/10';
      case 'profit': return 'bg-primary/10';
      case 'ratio': return 'bg-accent/10';
      default: return 'bg-muted/10';
    }
  };

  const formatValue = (value: number, category: string) => {
    if (category === 'ratio') {
      return value.toString() + (value < 50 ? '%' : ' months');
    }
    return '$' + value.toLocaleString();
  };

  const exportToPDF = async () => {
    if (!metrics.length) {
      toast({
        title: "No Data",
        description: "No financial data available to export.",
        variant: "destructive"
      });
      return;
    }

    // Track credit usage for export
    const canExport = await trackDownload('Financial Model PDF', 'Financial model export to PDF');
    if (!canExport) {
      return; // trackDownload already shows appropriate error messages
    }

    setIsExporting(true);
    try {
      // Create the PDF content element
      const element = document.getElementById('financial-model-content');
      if (!element) {
        throw new Error('Element not found');
      }

      const canvas = await html2canvas(element, {
        scale: 2,
        useCORS: true,
        backgroundColor: '#ffffff'
      });

      const imgData = canvas.toDataURL('image/png');
      const pdf = new jsPDF('p', 'mm', 'a4');
      
      const imgWidth = 210;
      const pageHeight = 295;
      const imgHeight = (canvas.height * imgWidth) / canvas.width;
      let heightLeft = imgHeight;
      let position = 0;

      // Add header
      pdf.setFontSize(20);
      pdf.text('Finlo Financial Model Report', 20, 20);
      pdf.setFontSize(12);
      pdf.text(`Generated on: ${new Date().toLocaleDateString()}`, 20, 30);
      
      position = 40;
      pdf.addImage(imgData, 'PNG', 0, position, imgWidth, imgHeight);
      heightLeft -= pageHeight;

      while (heightLeft >= 0) {
        position = heightLeft - imgHeight;
        pdf.addPage();
        pdf.addImage(imgData, 'PNG', 0, position, imgWidth, imgHeight);
        heightLeft -= pageHeight;
      }

      pdf.save(`finlo-financial-model-${new Date().toISOString().split('T')[0]}.pdf`);
      
      toast({
        title: "Export Successful",
        description: "Financial model exported as PDF successfully!"
      });
    } catch (error) {
      console.error('Export failed:', error);
      toast({
        title: "Export Failed",
        description: "Failed to export financial model. Please try again.",
        variant: "destructive"
      });
    } finally {
      setIsExporting(false);
    }
  };

  return (
    <Card>
      <CardHeader>
        <div className="flex items-center space-x-2">
          <Calculator className="w-6 h-6 text-primary" />
          <CardTitle>Interactive Financial Model</CardTitle>
        </div>
        <CardDescription>
          Hover over any metric to see AI-powered explanations of your financial data
        </CardDescription>
      </CardHeader>
      <CardContent className="space-y-6" id="financial-model-content">
        {/* Financial Metrics Grid */}
        <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">
          {metrics.map((metric, index) => (
            <TooltipProvider key={index}>
              <Tooltip>
                <TooltipTrigger asChild>
                  <div className={`p-4 rounded-lg border cursor-help hover:shadow-md transition-all ${getCategoryBg(metric.category)} hover:scale-105`}>
                    <div className="flex items-center justify-between mb-2">
                      <span className="text-sm font-medium text-muted-foreground">
                        {metric.label}
                      </span>
                      <HelpCircle className="w-4 h-4 text-muted-foreground" />
                    </div>
                    <div className={`text-2xl font-bold ${getCategoryColor(metric.category)}`}>
                      {formatValue(metric.value, metric.category)}
                    </div>
                  </div>
                </TooltipTrigger>
                <TooltipContent className="max-w-xs p-3">
                  <div className="space-y-2">
                    <p className="font-semibold">{metric.label}</p>
                    <p className="text-sm text-muted-foreground">
                      {metric.explanation}
                    </p>
                  </div>
                </TooltipContent>
              </Tooltip>
            </TooltipProvider>
          ))}
        </div>

        {/* Summary Cards */}
        <div className="grid gap-4 md:grid-cols-2">
          <Card className="bg-success/5 border-success/20">
            <CardContent className="p-4">
              <div className="flex items-center space-x-3">
                <TrendingUp className="w-8 h-8 text-success" />
                <div>
                  <p className="text-sm text-muted-foreground">Performance</p>
                  <p className="font-semibold text-success">Strong Growth</p>
                  <p className="text-xs text-muted-foreground">Revenue up 12% QoQ</p>
                </div>
              </div>
            </CardContent>
          </Card>

          <Card className="bg-primary/5 border-primary/20">
            <CardContent className="p-4">
              <div className="flex items-center space-x-3">
                <DollarSign className="w-8 h-8 text-primary" />
                <div>
                  <p className="text-sm text-muted-foreground">Profitability</p>
                  <p className="font-semibold text-primary">Above Average</p>
                  <p className="text-xs text-muted-foreground">18% net margin</p>
                </div>
              </div>
            </CardContent>
          </Card>
        </div>

        {/* Model Actions */}
        <div className="flex flex-wrap gap-3 pt-4 border-t">
          <Dialog open={showScenario} onOpenChange={setShowScenario}>
            <DialogTrigger asChild>
              <Button variant="outline" size="sm">
                <BarChart3 className="w-4 h-4 mr-2" />
                Run Scenario
              </Button>
            </DialogTrigger>
            <DialogContent className="max-w-4xl max-h-[90vh] overflow-y-auto">
              <DialogHeader>
                <DialogTitle>Financial Scenario Simulator</DialogTitle>
                <DialogDescription>
                  Test different revenue and expense scenarios to see their impact on your business.
                </DialogDescription>
              </DialogHeader>
              <ScenarioSimulator />
            </DialogContent>
          </Dialog>
          
          <Button 
            variant="outline" 
            size="sm" 
            onClick={exportToPDF} 
            disabled={isExporting}
          >
            <Download className="w-4 h-4 mr-2" />
            {isExporting ? 'Exporting...' : 'Export Model'}
          </Button>
          
          <Button variant="outline" size="sm">
            <Calculator className="w-4 h-4 mr-2" />
            Compare Periods
          </Button>
        </div>

        {/* Pro Tip */}
        <div className="bg-muted/50 rounded-lg p-4">
          <p className="text-sm text-muted-foreground">
            💡 <strong>Pro Tip:</strong> Click the info icons to get detailed AI explanations of each metric and how it impacts your business performance.
          </p>
        </div>
      </CardContent>
    </Card>
  );
};

export default InteractiveFinancialModel;