// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qjgnbvrxpmspzfqlomjc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFqZ25idnJ4cG1zcHpmcWxvbWpjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQ2Nzg1NzksImV4cCI6MjA5MDI1NDU3OX0.vxMwGVhQEAlgLx-ujWpBZ1bR9kSdB3CUSnD0y018ZN8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Disable detectSessionInUrl when a third-party OAuth callback is detected
// (QuickBooks uses ?realmId= which is never present in Supabase's own flows).
// Without this, Supabase mistakes the QB ?code=...&state=... for its own PKCE
// code, fails to exchange it, and wipes the session — logging the user out.
const _qbCallback = new URLSearchParams(window.location.search).has('realmId');

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: !_qbCallback,
  }
});