// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { isQuickBooksOAuthReturnInUrl } from '@/lib/supabase-third-party-oauth';

const SUPABASE_URL = "https://qjgnbvrxpmspzfqlomjc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFqZ25idnJ4cG1zcHpmcWxvbWpjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQ2Nzg1NzksImV4cCI6MjA5MDI1NDU3OX0.vxMwGVhQEAlgLx-ujWpBZ1bR9kSdB3CUSnD0y018ZN8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// QuickBooks OAuth uses ?code=&state= like Supabase PKCE; see supabase-third-party-oauth.ts
const _qbCallback = isQuickBooksOAuthReturnInUrl();

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: !_qbCallback,
  }
});